# SPDX-FileCopyrightText: Enno Hermann
#
# SPDX-License-Identifier: CC0-1.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/fsfe/reuse-tool
    rev: d6a8b11c3662ade803dcd3e585d49b78524e8bd5
    hooks:
      - id: reuse-lint-file
