# SPDX-FileCopyrightText: Enno Hermann
#
# SPDX-License-Identifier: MIT

name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: ./.github/actions/setup-uv
      - name: Lint check
        run: uv run pre-commit run --all-files
      - name: Mypy
        run: uv run mypy --strict src/
