# SPDX-FileCopyrightText: Enno Hermann
#
# SPDX-License-Identifier: MIT

name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.9"
            numpy-version: "--with numpy==1.21.6"
            torch-version: "--with torch==1.12.1+cpu"
          - python-version: "3.10"
            numpy-version: "--with numpy==1.21.6"
            torch-version: "--with torch==1.12.1+cpu"
          - python-version: "3.11"
            numpy-version: "--with numpy==1.24.4"
            torch-version: "--with torch==2.1.1+cpu"
          - python-version: "3.12"
            numpy-version: "--with numpy==1.26.4"
            torch-version: "--with torch==2.2.2+cpu"
          - python-version: "3.13"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.30"
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
      - name: Tests
        run: |
          uv run -v --python=${{ matrix.python-version }} \
            ${{ matrix.numpy-version }} ${{ matrix.torch-version}} \
            coverage run --parallel
      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: coverage-data-${{ matrix.python-version }}
          path: .coverage.*
          if-no-files-found: ignore
  coverage:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.30"
      - uses: actions/download-artifact@v4
        with:
          pattern: coverage-data-*
          merge-multiple: true
      - name: Combine coverage
        run: |
          uv python install 3.12
          uvx coverage combine
          uvx coverage html --skip-covered --skip-empty
          uvx coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
